# This is a basic workflow to help you get started with Actions

name: output

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/samdfonseca/pandoc_resume:latest
            ghcr.io/samdfonseca/pandoc_resume:1.0.0
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build html
        uses: ghcr.io/samdfonseca/pandoc_resume@latest
        id: html
        with:
          target: html
      - name: Build pdf
        uses: ghcr.io/samdfonseca/pandoc_resume@latest
        id: pdf
        with:
          target: pdf
      - name: Build docx
        uses: ghcr.io/samdfonseca/pandoc_resume@latest
        id: docx
        with:
          target: docx
      - name: Build rtf
        uses: ghcr.io/samdfonseca/pandoc_resume@latest
        id: rtf
        with:
          target: rtf
      
      - name: Archive build results
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            ./output/*.pdf
            ./output/*.docx
            ./output/*.html
            ./output/*.rtf
