# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install build tools
        run: sudo apt update -y && sudo apt install -y pandoc context make
      
      - name: Build html
        run: make html
      
      - name: Build pdf
        run: make pdf
      
      - name: Build docx
        run: make docx
      
      - name: Build rtf
        run: make rtf
      
      - name: Archive build results
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            ./output/*.pdf
            ./output/*.docx
            ./output/*.html
            ./output/*.rtf
